### PR TITLE
No longer include NUL character in aws_base64_encode output buffer length.

### PR DESCRIPTION
**Pull request by jonahharris**
*Issue #, if available:*

#123

*Description of changes:*

This change differentiates the length of the NUL-terminated string from that of the encoding itself.

**NOTE** - This _is_ a breaking change. Anything previously using this function, which decremented the length of the modified output buffer to account for the NUL terminator prior to passing it to aws_base64_decode, will break.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jonahharris** [comment]
Can someone tell me what the two failing builds are? I can't see the details.

**Comment by justinboswell** [comment]
> Can someone tell me what the two failing builds are? I can't see the details.
```
> ./format-check.sh 
tests/encoding_test.c failed clang-format check. 
```
Just run clang-format -i tests/encoding_test.c, and push the result.

**Comment by jonahharris** [comment]
That Windows test is taking forever... is it somehow stuck?

**Comment by JonathanHenson** [comment]
The windows docker image takes 20 minutes or so to boot, but it should have run by now, I’ll go kick it and see what’s going on

**Comment by jonahharris** [comment]
@JonathanHenson - Travis and that Windows build were a little flaky, but this is now good to go.

**Comment by jonahharris** [comment]
@JonathanHenson ready to merge

**Pull request merged**
