### PR TITLE
Clang tidy fixes

### PR DESCRIPTION
**Pull request by ColdenCullen**
- Add .clang-tidy file with default settings
  - Disable valist.Uninitialized, it triggers a false positive.
- Add asserts to aws_array_list_mem_swap to validate parameters.
- task_schedule.c: Add asserts to validate task functions before call.
    This is required because the analyzer doesn't know that
    aws_raise_error() always returns 1, so it can't make
    branch flow assumptions.
- Remove some trailing whitespaces.

After this PR is merged, running cmake with -DCMAKE_C_CLANG_TIDY="clang-tidy" will run clang-tidy as part of the build, and fail on any new errors.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ColdenCullen** [comment]
Yeah I'll give it a shot. I'm not sure if it's installed by default, but we can find out!

**Comment by ColdenCullen** [comment]
So it looks like we can't, because the build is running on Ubunutu 14.04 LTS, which only supports CMake 3.5. CMAKE_C_CLANG_TIDY was added in 3.6.

**Comment by JonathanHenson** [comment]
this isn't useful if it isn't in our CI, you'll need to find another way to run it.

**Comment by JonathanHenson** [comment]
also, it also doesn't work on Ubuntu 16.04

**Pull request merged**
