### PR TITLE
Fix stupid bad boolean logic in macro.

### PR DESCRIPTION
**Pull request by JonathanHenson**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by JonathanHenson** [comment]
Why y’all approving this? You know you have a better idea for that macro.

**Comment by ColdenCullen** [comment]
> Why y’all approving this? You know you have a better idea for that macro.

You said our suggestions wouldn't work :laughing:

**Comment by JonathanHenson** [comment]
See how much fun we have people? We’re hiring btw.

What I meant to say is your macro vars were wrong but your logic was better.  At least that second suggestion you made.

**Comment by ColdenCullen** [comment]
> What I meant to say is your macro vars were wrong but your logic was better. At least that second suggestion you made.

Oh yeah I was pseudo-coding lol. Who wants to write out `__GNUC_MINOR__` a million times

**Pull request merged**
