### PR TITLE
Marking unused parameters with AWS_UNUSED_PARAM macro.

### PR DESCRIPTION
**Pull request by jonahharris**
*Description of changes:*

This PR adds an AWS_UNUSED_PARAM(param) macro and respectively replaces all usages of the (void)param pattern. This makes identification of unused parameters simpler.

For context, I've been migrating a large database proxy system and compiler (of interest to AWS) from libevent/libuv over to AWS-C-IO. The code uses a number of portability/convenience macros, similar to those found in [Hedley](https://nemequ.github.io/hedley/api-reference.html), and I'm looking to add the commonly-useful ones to AWS-C-COMMON. Accordingly, I'll update the other common-based libraries (io, http, mqtt, etc.) to use any new addition as well.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jonahharris** [comment]
@ColdenCullen - I'm interested in your opinions/suggestions on how I should proceed with not only this PR, but also any potential additions to this (and related) libraries. Prior to any larger changes, other than bug-fixes or test additions, should I want to make a change, would you prefer I put it in an issue for discussion pre-development? I have no desire to bloat your libraries, I just want to add things I think are generally useful to other developers and that will be used/needed within my codebase.

**Comment by ColdenCullen** [comment]
Not sure why my opinion is worth bonus points, but my feelings are:
Pros:
* The macro is slightly clearer

Cons:
* Canceling out a parameter now requires significantly more text
* This change involves LOTS of churn

When in doubt, I tend to lean towards not making changes, but if anyone else on @awslabs/aws-sdk-common-runtime-team has feelings (looking at you @JonathanHenson), I could be swayed.

**Comment by jonahharris** [comment]
> Not sure why my opinion is worth bonus points

I went off the contributor graph and the cursory observation that I've seen the latest responses from you in terms of communication regarding issues and such :)

**Comment by JonathanHenson** [comment]
I don’t really care one way or the other as long as it is consistent. We did something similar in the c++ sdk years ago. One benefit of the macro is that it’s explicit about intent, and reduces cognitive load. If we do move forward with this, let’s update the coding guidelines as well. Also keep in mind, these header files will be included in the C++ SDK at some point and this macro will likely clash with its macro of the same name. Maybe put an ifdef check in there as well.

**Comment by JonathanHenson** [comment]
This looks fine to me. I’ll talk with the team today and make sure everyone wants to move forward with the change.

**Comment by jonahharris** [comment]
Cool. Thanks!

**Comment by JonathanHenson** [comment]
talked to team about it this morning. We can't find a compelling reason why this is better than it currently is. And while the change is fine, since we're neutral on it, we prefer to provide Occam's razor on changes.

Can you provide us with an argument for beyond the subjective argument I made about "explicit intent?"

**Comment by jonahharris** [comment]
The code I'm working on will soon be handed-over to AWS. To that end, I've already been making a considerable number of changes to switch from third-party libraries over to AWS-specific ones along with performing general clean-ups. Trust me, I get it: my position is similar to your team's in terms of, where possible, making the fewest changes required. In this case, for those things in my codebase that already seem cleaner, I'd just prefer not to make them less-so.

While I can always keep custom definitions within the codebase, it seemed this would be a good candidate for common, which I assume is why it was also added to the aforementioned C++ library.

While I get the default stance, aside from churn, I don't see a negative. Having made the related update to all but one other (public) library based on common, I've ensured 100% passing test coverage.

Regardless of this PR, I guess my question going forward is: how do we avoid this in the future? I'd like to hand over code that is relatively-clean and I'm happy to contribute to the base (-common and -io libraries on which this will be based), but I don't want to spend a couple hours working on something that isn't likely to be accepted. Any suggestions you or your team has would be appreciated.

**Comment by JonathanHenson** [comment]
We'd obviously always love your contributions. They're very much welcome. We also have a long roadmap of things that need improvement/implementation if you're looking for something in your spare time.

Regarding your last paragraph, I'd suggest opening an issue for us to dialog on to avoid churn for a large change. 

I'm still not against this, we're just mulling it over. I agree there's not really a negative here, we just also don't see the positive.

**Comment by jonahharris** [comment]
Cool. I'll open an issue on any future proposed change. This was a simple one, but I was definitely wondering how you would like to handle anything not-straight-forward. As an example: https://github.com/awslabs/aws-c-common/issues/123#issuecomment-495848822

**Comment by jonahharris** [comment]
While going through the IOT library samples I noticed it also has a similar macro, IOT_UNUSED.

**Comment by jonahharris** [comment]
I now have three full database protocol implementations rewritten with aws-c-common and aws-c-io; is this still iffy in terms of being merged? If the team if pro-merge, I'll run through and make sure it's up-to-date with master. If not, I'll just update my local definitions to use something other than AWS_UNUSED.

**Pull request closed without merging**
