### PR TITLE
Replace abort() with assert(0) so that CBMC catches it

### PR DESCRIPTION
**Pull request by angelhof**
Currently abort() is not caught as an error by CBMC, and this could lead to failed assertions in `AWS_FATAL_ASSERT` to be missed. 

I created this as a draft PR to see which proofs fail after this change.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danielsn** [comment]
you could also make ```AWS_FATAL_ASSERT``` turninto ```assert``` in CBMC mode.

**Comment by angelhof** [comment]
> you could also make `AWS_FATAL_ASSERT` turninto `assert` in CBMC mode.

That would certainly make sense together with replacing `abort()` with `assert(0)`. I will do that.

**Comment by angelhof** [comment]
Note: The CBMC proof error here seems to be the same as in #430, so I will not debug this before #430 is merged.

**Comment by angelhof** [comment]
The error in downstream seem to be unrelated to this PR.
```
/tmp/build/downstream/aws-c-http/tests/test_connection.c:24:10: fatal error: 'aws/io/log_writer.h' file not found 
#include <aws/io/log_writer.h> 
         ^~~~~~~~~~~~~~~~~~~~~ 
1 error generated. 
```

**Comment by ColdenCullen** [comment]
PLEASE DON'T MERGE THIS YET. @graebm is running into similar issues and may need to glue more changes onto this.

**Comment by angelhof** [comment]
@ColdenCullen @graebm any update on that? Can we merge this?

**Pull request merged**
