### PR TITLE
Fix compiler errors with MinGW compilers

### PR DESCRIPTION
**Pull request by Biswa96**
* Description of changes:

  - Windows: Check _MSC_VER for MSVC specific pragma warnings directives. `#pragma warning` is Microsoft Visual Compiler specific and creates warning with GCC as those are unknown.
  - include/common: Check _WIN32 to prevent htonl and ntohl functions. This replaces checking `_MSC_VER`  as we need to check if the platform is Microsoft Windows or not. So, `_WIN32` is proper preprocessor to check it.
  - tests: Check if alloca is already defined. GCC has `alloca` already defined to `__builtin_alloca`.
 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Biswa96** [comment]
Also if I enable `BUILD_SHARED_LIBS` the following error is shown at CMake configure time:

```cmake
CMake Error: install(EXPORT "aws-c-common-targets" ...) includes target "aws-c-common" more than once in the export set.
```

**Comment by Biswa96** [comment]
Ping! Any comment on this pr?

**Comment by Biswa96** [comment]
Ping.

**Comment by bretambrose** [comment]
Merged in https://github.com/awslabs/aws-c-common/pull/772

**Pull request closed without merging**
