### PR TITLE
Add aws-c-s3 and aws-c-iot as downstream projects

### PR DESCRIPTION
**Pull request by graebm**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by justinboswell — COMMENTED** [review]
Shouldn't these be downstream of aws-c-http and aws-c-mqtt respectively? downstreams are evaluated recursively

**Review by TingDaoK — APPROVED** [review]

**Comment by graebm** [comment]
> Shouldn't these be downstream of aws-c-http and aws-c-mqtt respectively? downstreams are evaluated recursively

You tell me!
All the other builder.json files only list their immediate upstream dependencies, they don't list their downstreams.
I was wondering how aws-crt-builder gathered the whole tree and assumed this file was the source of truth.

**Comment by justinboswell** [comment]
> > Shouldn't these be downstream of aws-c-http and aws-c-mqtt respectively? downstreams are evaluated recursively
> 
> You tell me!
> All the other builder.json files only list their immediate upstream dependencies, they don't list their downstreams.
> I was wondering how aws-crt-builder gathered the whole tree and assumed this file was the source of truth.

Should also be immediate downstreams. I know it's currently missing some, but I'm trying to keep the graph a graph without building a database for now.

**Comment by graebm** [comment]
nope. this isn't how it's done...

**Pull request closed without merging**
