### PR TITLE
Make it compile on Cygwin.

### PR DESCRIPTION
**Pull request by Bu11etmagnet**
Signed-off-by: Bu11etmagnet <Bu11etmagnet@users.noreply.github.com>

https://github.com/aws/aws-sdk-cpp/issues/1143

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinboswell** [comment]
Once CI passes (which it should now that I've updated the branch), this should be good to go. Thanks!

**Comment by justinboswell** [comment]
source/arch/cpuid.c failed clang-format check. 

If you just run clang-format -i source/arch/cpuid.c and commit the results, that should fix it.

**Comment by jkmartin19** [comment]
Can I get an update on this? I haven't been able to get this library to build on Windows 7 at all, including trying Cygwin, so I am hoping this will fix my issue. Any idea when this will be merged?

**Comment by Bu11etmagnet** [comment]
Had to downgrade clang because the latest clang-format on Cygwin is non-functional :(
Could somebody check the failed builds - I don't have an AWS account.

**Comment by feliperodri** [comment]
> Had to downgrade clang because the latest clang-format on Cygwin is non-functional :(
> Could somebody check the failed builds - I don't have an AWS account.

@Bu11etmagnet both build errors are related to format check on the `source/arch/cpuid.c` file. You can reproduce this error by running `./format-check.sh` and you can automatically fix the format by running `clang-format -i source/arch/cpuid.c`.

**Comment by Bu11etmagnet** [comment]
That's odd, I ran clang-format now.
How is `aws-c-common-linux-clang6-x64` and `aws-c-common-linux-clang8-x64` different from the rest?

**Comment by singku** [comment]
@justinboswell  Any plan to merge it?

**Comment by jkmartin19** [comment]
This PR has been open for over 3 weeks. Are there plans to merge it, or should I find a different way to build these libraries?

**Pull request merged**
